homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 4
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named customize/
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant


# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

updater:
  reporting: False

custom_updater:
  hide_sensor: False
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Cloud
cloud:

python_script:

light:
  - platform: switch
    name: Hatt lampa
    entity_id: switch.tradfri_control_outlet
  - platform: switch
    name: Tv-bänk
    entity_id: switch.tv_bank


input_boolean:
  vacation_mode:
    name: Vacation mode
  guests_mode:
    name: Guest mode
  morning:
    name: Morning
  day:
    name: Day
  evening:
    name: Evening

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_bot_api
    allowed_chat_ids:
      - !secret telegram_bot_chat_ids


#mqtt:
#  broker: 192.168.1.13
#  port: 1883
#  client_id: home-assistant-1
#  username: !secret mqtt_user
#  password: !secret mqtt_password

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_aqara_key

# Text to speech
tts:
  - platform: google

automation: !include_dir_merge_list automation/
device_tracker: !include_dir_merge_list device_tracker/
group: !include_dir_merge_named group/
media_player: !include_dir_merge_list media_player/
cast: !include_dir_merge_named /googel_cast
notify: !include_dir_merge_list notify/
script: !include_dir_merge_named script/
sensor: !include_dir_merge_list sensor/



zone: !include zones.yaml