homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 4
  unit_system: metric
  time_zone: Europe/Stockholm
  packages: !include_dir_named packages
  auth_providers:
   - type: homeassistant

# Enables the frontend
frontend:
  themes: !include themes.yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

recorder: !include logging/recorder.yaml
history: !include logging/history.yaml
logbook: !include logging/logbook.yaml
logger: !include logging/logger.yaml

updater:
  reporting: False

system_health:

custom_updater:
  hide_sensor: False
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

# Cloud
cloud:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

automation: !include_dir_merge_list automation/
zone: !include zones.yaml