#- alias: Send message at a given time
#  trigger:
#    platform: time
#    at: "22:00:00"
#  action:
#    service: notify.calle
#    data:
#      message: 'Time for bed'


#- alias: Calle_home
#  trigger:
#    platform: state
#    entity_id: device_tracker.callehtc10
#    state: 'home'
#  action:
#    service: notify.pushbullet
#    data:
#      message: 'Time for lunch'
#      target: device/HTC10

- alias: On startup
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: notify.calle
      data_template:
        title: "*Info*"
        message: "Home Assistant has started."

- alias: On shutdown
  trigger:
    platform: homeassistant
    event: shutdown
  action:
    - service: notify.calle
      data_template:
        title: "*Info*"
        message: "Home Assistant has shutdown."
