- alias: Send message at a given time
  trigger:
    platform: time
    hours: 22
    minutes: 0
    seconds: 0
  action:
    service: notify.pushbullet
    data:
      message: 'Time for bed'
      target: device/HTC10


#- alias: Calle_home
#  trigger:
#    platform: state
#    entity_id: device_tracker.callehtc10
#    state: 'home'
#  action:
#    service: notify.pushbullet
#    data:
#      message: 'Time for lunch'
#      target: device/HTC10
