- alias: Send message at a given time
  trigger:
    platform: time
    hours: 22
    minutes: 0
    seconds: 0
  action:
    service: notify.pushbullet
    data:
      message: 'Time for bed'
      target: device/HTC10


#- alias: Calle_home
#  trigger:
#    platform: state
#    entity_id: device_tracker.callehtc10
#    state: 'home'
#  action:
#    service: notify.pushbullet
#    data:
#      message: 'Time for lunch'
#      target: device/HTC10


- alias: If there is motion and night turn on the gateway light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001f9d45b
    from: 'off'
    to: 'on'
  condition:
    condition: time
    after: '23:15:00'
    before: '05:00:00'
  action:
    - service: light.turn_on
      entity_id: light.gateway_light_7811dcb8f3c0
      data:
        brightness: 4

- alias: If there no motion for 1 minutes turn off the gateway light
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001f9d45b
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    condition: time
    after: '23:10:00'
    before: '05:05:00'
  action:
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcb8f3c0
      
- alias: If door opens
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001fa3524
    from: 'off'
    to: 'on'
  action:
    service: notify.telegram
    data_template:
      title: "INFO"
      message: "Door opens"
