homeassistant:
  customize:
    light.gateway_light_7811dcb8f3c0:
      friendly_name: Xiaomi gateway  #light

## Trådfri ##
## Lampor ##
#light.tradfri_bulb_e14_w_opch_400lm:
#  friendly_name: "Fönsterlampa"
#light.tradfri_bulb_e27_ws_opal_980lm:
#  friendly_name: Matbord
## Outlet ##
#switch.tradfri_control_outlet:
#  friendly_name: Adventsljusstake
## Grupper ##
#light.fonster:
#  friendly_name: "IKEA group fönster"
#  hidden: true
#light.vardagsrum:
#  friendly_name: IKEA group vardagsrum
#  hidden: true

light:
  - platform: switch
    name: Hatt lampa
    entity_id: switch.tradfri_control_outlet
  - platform: switch
    name: Tv-bänk
    entity_id: switch.tv_bank
