vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.16
    token: !secret xiaomi_vacuum
    name: Dammbot

sensor:
  - platform: template
    sensors:
      dammbot_status_sensor:
        friendly_name: Dammbot status sensor
        value_template: >-
          {{ states.vacuum.dammbot.attributes.status }}

automation: 
  - alias: Dammbot status message
    trigger:
      - platform: state
        entity_id: vacuum.dammbot
    action:
      - service: notify.calle
        data:
          title: '*Dammbot*'
          message: >-
            {{states.sensor.dammbot_status_sensor.state}}

  - alias: Dammbot klar
    trigger:
      - platform: state
        entity_id: vacuum.dammbot
        from: 'returning'
        to: 'docked'
    action:
      - service: notify.malin
        data:
          title: '*Dammbot*'
          message: Jag har dammsugit klart och är tillbaka på min plats
          data:
            push:
              thread-id: "dammbot"