sensor:
  - platform: vasttrafik
    key: !secret vasttrafik_key
    secret: !secret vasttrafik_secret
    departures:
#      - name: 121
#        from: Lindholmen
#        heading: Volvo Torslanda PV
#        delay: 2
      - name: 16
        from: Lindholmen
        heading: Chalmers
#        delay: 2
#      - name: 55
#        from: Lindholmsplatsen
#        heading: Sven Hultins Plats
#        delay: 1
      - name: Stan
        from: Lindholmen
        heading: Nordstan
#        delay: 2
      - name: Färja
        from: LindLindholmspiren
        heading: Stenpiren
        lines:
          - 286
#        delay: 5
